### ISSUE TITLE
ScoutProf-triggered SEGFAULT

### ISSUE THREAD

**Issue by itsderek23** [scoutapp/scout_apm_ruby#108]
A user reported a `SEGFAULT` when running Scout on his local development computer w/ScoutProf. 

* [Backtrace](https://gist.github.com/itsderek23/673780bda7499f7cf370e5d4368e31d8)
* `ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]`

Two exception backtraces were sent - the first doesn't have the full backtrace, but points to the location where ScoutProf is started:

```
/Users/zdrummond/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/scout_apm-3.0.0.pre10/lib/scout_apm/tracked_request.rb:193: [BUG] Segmentation fault at 0x007ffdec7cd730
```

**Comment by dlanderson** [comment]
Our 3.x agent is deprecated and not suggested to use due to stability issues. Our latest 2.x is stable and includes a replacement for ScoutProf (the only feature different in the 3.x line) called AutoInstruments. You can read more about AutoInstruments here:

[https://scoutapm.com/blog/introducing-autoinstruments-zero-effort-performance-monitoring-of-custom-ruby-code](https://scoutapm.com/blog/introducing-autoinstruments-zero-effort-performance-monitoring-of-custom-ruby-code)
[https://docs.scoutapm.com/#autoinstruments](https://docs.scoutapm.com/#autoinstruments)
[https://docs.scoutapm.com/#autoinstruments-faq](https://docs.scoutapm.com/#autoinstruments-faq)

**Comment by ryan-sherpa** [comment]
Brutal error, gents. Took us a while to track this down. At the peak we were hitting Heroku H13 (segfaults) on 0.25% of requests due to this. 
![Screen Shot 2020-12-12 at 4 55 59 PM](https://user-images.githubusercontent.com/14316723/102000592-d3731a00-3c9d-11eb-9dbe-5502869f1a8d.png)

**Comment by dlanderson** [comment]
@ryan-sherpa My apologies - ScoutProf never made it out of Beta due to stability issues. We're updating docs and old blog posts to make sure it's clear ScoutProf is deprecated
