### ISSUE TITLE
Investigate ScoutProf throttling when CPU-constrained

### ISSUE THREAD

**Issue by itsderek23** [scoutapp/scout_apm_ruby#109]
We've heard a couple reports of ScoutProf adding significant overhead. We'd expect this to normally be in the 5 ms range, but these report more overhead:

![image](https://user-images.githubusercontent.com/7880/28074498-f3179afa-6615-11e7-8477-299fcf45b0c7.png)

One possible factor: in the above screenshot, the CPU usage averaged 40% for the Rails processes prior to running the ScoutProf BETA. That's decent CPU usage for the Rails processes. Running ScoutProf - which consumes CPU - may tip things over, similar to the type of behavior [described here](https://www.iron.io/how-we-went-from-30-servers-to-2-go/).

If we think it's just a resource problem, we should discuss some ways to automatically throttle ScoutProf down (increasing the sample interval or completely turn off) if we detect the host node is swamped.

A basic, non-intelligent step: add a config option for the ScoutProf sampling interval. This could at least isolate if the sampling rate is a driver for this problem.

/cc @dlanderson @cschneid

**Comment by dlanderson** [comment]
Our 3.x agent is deprecated and not suggested to use due to stability issues. Our latest 2.x is stable and includes a replacement for ScoutProf (the only feature different in the 3.x line) called AutoInstruments. You can read more about AutoInstruments here:

[https://scoutapm.com/blog/introducing-autoinstruments-zero-effort-performance-monitoring-of-custom-ruby-code](https://scoutapm.com/blog/introducing-autoinstruments-zero-effort-performance-monitoring-of-custom-ruby-code)
[https://docs.scoutapm.com/#autoinstruments](https://docs.scoutapm.com/#autoinstruments)
[https://docs.scoutapm.com/#autoinstruments-faq](https://docs.scoutapm.com/#autoinstruments-faq)
