### ISSUE TITLE
Too much "info" logs

### ISSUE THREAD

**Issue by DamienMetzger** [scoutapp/scout_apm_ruby#130]
Hello,

My server logs are full of "info" logs written by scout, which should be - I think - written as "debug" logs.
I don't really care what scout is "instrumenting"  or "attempting".

The only logs that can be "info" are the last 2 lines or the init :

INFO : Scout Agent [2.1.32] Initialized
INFO : Sending Application Startup Info - App Server: webrick, Framework: Rails, Framework Version: 5.0.6, Database Engine: postgres

Thank you,

Damien

**Comment by cschneid** [comment]
Sorry for the noise.

Normally those logs will be in log/scout_apm.log, away from your normal application logs. We've found the default `info` level pretty helpful for debugging situations that crop up on people's servers.

If they're too noisy for you, you can silence them significantly with the `log_level` option. (either in the `scout_apm.yml` file, or via the `SCOUT_LOG_LEVEL` environment variable). Set that to `warn` or `error` to get nearly no log messages.

Let us know at support@scoutapp.com if you run into any other issues.

**Comment by dlanderson** [comment]
From Slack:

> When I run the console on Heroku I see: Agent attempting to load in interactive mode

That message should probably be changed to an `info` instead of the current level, `warn`

> The follow-up message is, which sounds like things are ok: WARN : Deferring agent start. Standing by for first request

That needs a bit of rework to not be alarming in the console when things are OK.


Perhaps each precontition specifies its own log level instead of all preconditions being a warning?
https://github.com/scoutapp/scout_apm_ruby/blob/master/lib/scout_apm/agent/preconditions.rb#L54
