### ISSUE TITLE
Using DevTrace in a webpack application

### ISSUE THREAD

**Issue by adaam2** [scoutapp/scout_apm_ruby#132]
Reading over the source of Scout Instant, I can see that for `XMLHttpRequest` requests, your middleware grabs the `X-scoutapminstant ` header from the response body of the request and passes it to the `ScoutInstant` instance on the window object. I'm running an API instance separately to a webpack based React app, and would love to be able to get the DevTrace profiler to display on my frontend. Is there a way to proxy DevTrace or by any other means inject it into my frontend application so that I can profile requests to my API (both apps are running in Docker)

**Comment by cschneid** [comment]
Single page apps are a bit tricky right now, and will likely remain so until I get a chance to rework how DevTrace's javascript is injected and bootstraps itself.

To clarify your architecture, is it:

```
Browser loads React HTML/JS from `react-builder-docker:3000`.
Browser runs future api calls to a rails server at `rails-api-docker:3000`?
```

So the issue is that the DevTrace javascript isn't even being injected into the React page, and hence the header is ignored even though it is sent by the Rails API on each request?

**Comment by adaam2** [comment]
Hi @cschneid 

Yes, they are separate applications running in separate containers. They all run on the same docker network (e.g. `docker network create`). So whilst we receive the devtrace headers back in the response headers for requests we make to the API container instance, I guess what's missing in DevTrace currently is a portable way of injecting the DevTrace JS widget into a client application.
