### ISSUE TITLE
5+ second require of scout_apm gem due to webrick

### ISSUE THREAD

**Issue by drewblas** [scoutapp/scout_apm_ruby#143]
In doing some optimizations, I found that adding the scout_apm gem to a rails app adds ~5 seconds to boot and load times.

I created a proof-of-concept app to demonstrate.  Here's a completely stripped down blank app: https://github.com/drewblas/scout_slow_load_poc

I traced the culprit to `require 'webrick'`.  

I'm wondering if it's possible to remove this hard dependency on loading webrick.  (Most Rails devs I'm sure would tell you they have no desire to load webrick at all, especially in production!)

My further digging found two different sets of use of Webrick:

1. As an instrumentation target (same as Unicorn, Passenger, etc).  The `ServerIntegration` seems properly scoped to act correctly even if webrick isn't loaded (just like all the others).  So it's not needed for that
2. It's used to actually **RUN** a webrick server as part of `ScoutApm::Remote::Server`.  However, this only appears to be used by `test/unit/remote/test_server.rb` and `lib/scout_apm/background_job_integrations/resque.rb`.   

Would it be possible to remove the global `require 'webrick'` and:

1.  Only require it for the test suite
2.  And only require it if the app is actually using `resque`?  (IMHO even if you are using resque, I would very much not like to have a behind-the-scenes webrick server running in prod)

**Comment by cschneid** [comment]
I am surprised that the webrick require is so expensive.  I'll move the require to be used only in the spot where it's needed in our next release. 

For the uses of webrick: 

1. you're right that webrick is an instrumentation target, and we don't go requiring it there (just check if it exists).
2. Resque required some tricks to instrument. Because it forks and exits a new process for each individual job execution. We have to have a way to collate those recordings in the agent - so the most compatible & simple approach was to launch an simple webrick server in the resque parent, and use that to move the single trace of the job back to the persistent resque parent process.  That webrick is only launched for resque, and is bound to 127.0.0.1 by default (not allowing outside communication), and a high port.

**Comment by cschneid** [comment]
Released in 2.3.5
