### ISSUE TITLE
DevTrace triggers failed XHR requests w/large response headers

### ISSUE THREAD

**Issue by sdemjanenko** [scoutapp/scout_apm_ruby#148]
I found that XHRs were returning 502 response codes because the DevTrace middleware was attaching a large header which was overwhelming my development server's nginx buffer. I increased the buffer size and the error went away.

**Comment by itsderek23** [comment]
Note that this may appear in Chrome DevTools Console w/the error message "Failed to load resource: net::ERR_RESPONSE_HEADERS_TOO_BIG"

**Comment by synth** [comment]
Hitting this as well when accessing our site via ngrok

**Comment by ioquatix** [comment]
58KB in a single header!? As someone who implemented both HTTP/1, and HTTP/2, client & servers in both Ruby and C++, I'm having a 
![source](https://user-images.githubusercontent.com/30030/64473894-b610ef80-d1c0-11e9-8161-2819dc918ac4.gif)

Sorry, I didn't add anything to the issue. 58KB is a lot of data to put in a header.

**Comment by synth** [comment]
Took a stab at an initial PR to add compression support in #282 ^

**Comment by synth** [comment]
How come this was closed? I got the notification of this being closed and couldn't remember the initial context from 2019 and then separately was using DevTrace again and ran into this exact issue. Ended up finding this issue and my PR. I fetched upstream into my PR and it worked perfectly to address this issue. Guessing it was closed since no one else appears to encountering this. IMHO, header compression should still be considered :)
