### ISSUE TITLE
Use with Octoshark gem `stack level too deep` exception

### ISSUE THREAD

**Issue by drl123** [scoutapp/scout_apm_ruby#217]
Trying to replace NewRelic with Scout in our Rails 5.0 app (ActiveRecord v5.0.3).  We use Octoshark to manage sharding of user data into multiple db's, and the main db uses the default AR connection.   I'm getting a `stack level too deep` exception when the instrumenter tries to run the query against the shards.  I've tried the 2.4.17, 2.4.11 and 3.0.0-pre28 (after looking through the issues about `prepend`)and they all do the same.  Any suggestions for how to configure these two gems to be compatible?  (I have pulled the NR gem completely out too, so I know it isn't a collision between instrumenters and NR instrumented these just fine with no config changes).

![screen shot 2018-09-06 at 1 04 39 pm](https://user-images.githubusercontent.com/568926/45173489-54e1c500-b1d6-11e8-824f-1729ce7ade1f.png)

**Comment by cschneid** [comment]
@drl123 This [line](https://github.com/dalibor/octoshark/blob/master/lib/octoshark/active_record_extensions.rb#L24) in Octoshark is the issue.

Ruby's metaprogramming has evolved awkwardly over the years. Scout [overrides](https://github.com/scoutapp/scout_apm_ruby/blob/master/lib/scout_apm/instruments/active_record.rb#L175) the ActiveRecord `log` method with a tracing version. To support older versions of Ruby, we use the `alias_method` approach to overriding.

Both approaches work in isolation, but the interaction of the two overriding the same method can cause loops like this.

We have some experimental code to attempt to support both (See #178 for an example), but haven't yet settled on this approach since it adds a fair bit of complexity.

**Comment by drl123** [comment]
Thanks @cschneid...I did see that issue and a few others which is why I tried the various versions and didn't see any way to configure it for `prepend` vs `alias_method`.  Unfortunately, this is a show-stopper for us to make the switch to Scout as changing the sharding gem is a much more invasive endeavor.  If you do get resolution, please let me know.  We're eager to try out your platform.  I'd be happy to test any proposed solutions too.

**Comment by Zeneixe** [comment]
We have the same issue, we're looking at using scoutapp but we can't part from octoshark. Any ETA for a fix?

**Comment by dlanderson** [comment]
@ioquatix would be awesome to address this. We did some work in https://github.com/scoutapp/scout_apm_ruby/pull/178 last year but we need to review that progress and whether it's still the best option.

**Comment by ioquatix** [comment]
Okay I’ll take a look

**Comment by ioquatix** [comment]
Sorry for the delay, I'll investigate this now.

**Comment by ioquatix** [comment]
Okay, I could repro which is a good sign.

**Comment by ioquatix** [comment]
Okay, I have a repro and a fix: https://travis-ci.org/scoutapp/scout_apm_ruby/jobs/554079006 shows green, I think we are clear to land this on master.

**Comment by ioquatix** [comment]
This has been merged into master. Hopefully in the next release, it's fixed.

@drl123 can you please try it out and report back? I'll close this issue, but feel free to open a new one if there are still issues.

**Comment by drl123** [comment]
Thanks guys.  We'll give it a try when we get caught up on some critical projects.  This is our busiest time of the year, so it may take us some time to get to it.
