### ISSUE TITLE
Memory leak when monitoring is disabled (reproducible, steps are known)

### ISSUE THREAD

**Issue by flexoid** [scoutapp/scout_apm_ruby#228]
Hi.

We discovered a serious bug which is almost failed our production setup by consuming all available memory, mostly by the background worker (DelayedJob) processes.

We have `monitor: false` (!!!) for that server as we didn't plan to trace it for that time, and a picture like that.

![image](https://user-images.githubusercontent.com/335778/48543254-3123b500-e8d2-11e8-988c-3b3afdf049e4.png)

After some time in heap dump analyzing I found out that there are too many old objects like `ScoutApm::MetricSet`, `ScoutApm::NumericHistogram` and other related to `ScoutApm`.

A fast code review and further process memory analyzis revealed that `ScoutApm::AgentContext#request_histograms_by_time` contains a huge amount of objects (32k+).

As I understand, [this line](https://github.com/scoutapp/scout_apm_ruby/blob/f2341535e6cba67b045632b9699d530a48128a15/lib/scout_apm/agent.rb#L149) explicitly specifies that `BackgroundWorker`, which should collect all this old histograms, is not started if monitoring is disabled, but looks like metrics are collected anyway (installed [here](https://github.com/scoutapp/scout_apm_ruby/blob/f2341535e6cba67b045632b9699d530a48128a15/lib/scout_apm/agent.rb#L42)).

Please, contact me if you'll need additional information.

**Comment by cschneid** [comment]
I believe what's happening is that we treat the Sidekiq (and resque, and so on) instruments differently than library (ActiveRecord, HTTP, etc) instruments.

You pointed to the exact line that looks wrong. The library instruments are behind that check of `should_load_instruments?` which does the `monitor` check.  Somehow the background instruments don't have that check.

So what's happening is that a bit too much is installed, and the sidekiq instruments are capturing some data, but since the rest of the agent is (correctly) not started, that data never moves forward and out from through normal means, so it slowly grows over the course of several days.

I'll have a new version out to you in a bit that will prevent Sidekiq from being instrumented at all when `monitor = false`.

Thank you for the excellent report, we'll have it fixed right away.

**Comment by cschneid** [comment]
#231 should fix this. I'm going to do some more testing before fully releasing it.

**Comment by cschneid** [comment]
@flexoid - I merged and deployed this in 2.4.21. Thanks again for the excellent report.
