### ISSUE TITLE
Retry after failed request?

### ISSUE THREAD

**Issue by SvenSchoene** [scoutapp/scout_apm_ruby#244]
Hey,

I was wondering how a failed request to Scout is handled? Is it being retried (maybe with backoff, like Sentry is doing)? Or is it considered ok to lose  a few requests here and there by design? From what I found in the source code there is a bit of sampling going on and e.g. being selective about capturing traces because it's not entirely cheap for doing so.

I couldn't however find a conclusive answer, neither in the codebase, nor in the docs.

**Comment by cschneid** [comment]
Two distinct questions here I'll answer:

:one: **What happens when your application has an error**. The agent marks 500 errors, and we capture the count of those into the overview charts. And if the request was "interesting" enough, we get a detailed trace for it as well.

:two: **What happens when the Agent can't report to APM's ingest**. Right now, the ruby agent doesn't attempt to retry. If a report fails, it gets dropped. This behavior is based on a preference to simplify the agent, to keep it from causing issues in a customer's application. We've never run into an issue where networking or our ingest servers were an issue capturing reports from the agent.

**Comment by SvenSchoene** [comment]
Thanks for the detailed answer, it's appreciated! 👍
