### ISSUE TITLE
Memory leak detected in Rails 6 beta app

### ISSUE THREAD

**Issue by jsierles** [scoutapp/scout_apm_ruby#273]
We noticed a pretty nasty leak in our app, and `derailed_benchmarks` gave these results after 1000 requests against an endpoint that only makes one ActiveRecord query.

```
allocated memory by gem
-----------------------------------
 228945722  rails-c81d6448ad2d
 135322501  scout_apm-2.5.1
 11591000  rack-2.0.7
```

Scout also reported retaining `ScoutApm:: HistogramBin` objects across requests. I can provide more details, but wondered if anyone else has already identified an issue here?

**Comment by cschneid** [comment]
Hi @jsierles - 

We are not aware of any leaks in the Ruby agent. We will fix any ASAP if they come up.

Are those allocated metric numbers all memory allocated, including any that is GC'd, or memory still held at the end? We do create and toss a fair bit number of objects in the process of instrumenting a transaction. There's not much way around that unfortunately.

The agent does keep track of histograms between requests, so that's to be expected. The algorithm we use is an approximate histogram with a fixed size [1]. We actually keep two histograms per endpoint, one is cleared each minute, and used to report that minute's 95th percentile, and the other is held onto forever, and used to determine the best candidates for full traces.

[1]: An Array of 50 pairs of floats per named endpoint. So in your described case, just two of these sets (one per-minute, and one permanent).

**Comment by jsierles** [comment]
Thanks, that information was helpful. I'll report more if I can identify leakage. In this case I still see leaks even when removing Scout, so I'll close this issue for now.
