### ISSUE TITLE
Any plans to upgrade `proc/wait3`

### ISSUE THREAD

**Issue by mobilutz** [scoutapp/scout_apm_ruby#353]
Is there any plans, to use the current `proc/wait3` gem directly?
https://github.com/djberg96/proc-wait3

I am asking specifically, because they changes their license last year to `Apache-2.0` and maybe this gem can follow that change and not rely on `Artistic License 2.0` anymore.
https://github.com/djberg96/proc-wait3/commit/aecd3168120206351b5a3a1bee70e2a7be43bb8e

**Comment by cschneid** [comment]
Closing this, but to clarify the state of things:

We don't use proc/wait3 at all. We use a customed version of a C extension that was borrowed from "rusage" gem, which in turn was extracted from a version of Wait3 (hence, inheriting that Artistic License for that code).

Since the newer version of wait3 also has the same [C extension](https://github.com/djberg96/proc-wait3/blob/main/ext/proc/wait3.c#L736), we could relicense without harm I believe. 

Can you clarify why you'd want to shift from Artistic to Apache? Neither "infects" or otherwise apply to any users of a library, including using ScoutAPM. As a customer you shouldn't need to care.
